#pragma once
// ==============================================================================
// WeaR-studio GPU filter interface
// IRhiFilter.h - Bridge between IFilter plugins and the Qt RHI compositor
// ==============================================================================

#include <QVector4D>

namespace WeaR {

enum class RhiFilterKind {
    None = 0,
    ChromaKey = 1,
    GaussianBlur = 2,
    ColorCorrection = 3
};

/**
 * @brief Parameters consumed by the shared RHI fragment shader.
 *
 * The layout is four vec4 values so the data maps cleanly to a 64-byte
 * std140-style uniform block across GLSL/HLSL/MSL generated by qsb.
 */
struct RhiFilterUniforms {
    QVector4D filter0;
    QVector4D filter1;
    QVector4D filter2;
    QVector4D filter3;
};

/**
 * @brief Optional GPU extension implemented by built-in or plugin filters.
 *
 * IFilter remains the public plugin contract. Filters that also implement this
 * interface can be evaluated directly in the RHI compositor. Filters that do
 * not implement IRhiFilter automatically use the QPainter/CPU path.
 */
class IRhiFilter {
public:
    virtual ~IRhiFilter() = default;

    [[nodiscard]] virtual RhiFilterKind rhiFilterKind() const = 0;
    [[nodiscard]] virtual RhiFilterUniforms rhiUniforms() const = 0;
};

} // namespace WeaR
